### ISSUE TITLE
Bug:  Copilot can't get the HMD during start up

### ISSUE THREAD

**Issue by vincione** [Project-Hatchet/public_h-60#120] opened 2021-03-16 23:25 UTC
If the Copilot is on the chopper before it is started he can't get the HMD, he needs to get out and get in to make it work once the chopper is started.

**Comment by BroBeansCPG** [comment] 2021-03-16 23:42
Following the bug report template is highly encouraged, it's not as daunting as it looks 

Also, is this version 0.30 or RC 0.3.1?

**Comment by vincione** [comment] 2021-03-17 08:39
RC 3.0.1

**Comment by Kill3rCat** [comment] 2021-07-13 16:03
Not sure if I should've created a new issue, but I am able to repro this issue, had it last night while testing, and also had it about a year ago when testing an older version of the mod (the one that crashed every 30 min)

In our case, the co-pilot and pilot enabled their HMD through the FMS when the aircraft was in a power-on, but not engine-on state. Neither HMD came on, though that's probably intended behaviour. When the aircraft's engines were turned on, the pilot's HMD came on properly, but the co-pilot reported his HMD appearing for a split second and then disappearing again; the issue was fixed by the co-pilot taking control of the aircraft and then releasing control, after which both pilot and co-pilot had their HMD working.

**Closed as completed** 2022-09-08 14:05 UTC
Labels: Type: Bug, Status: Cant reproduce
