### ISSUE TITLE
Model: Right Door Gunner Seating position

### ISSUE THREAD

**Issue by Halliwedge** [Project-Hatchet/public_h-60#138] opened 2021-04-19 15:20 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [y] I checked the documentation and found no answer
- [y] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [y] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord
  

# Model Error report 

## **Description:**

- Minor placement error of the Right Door Gunner. Any player/AI seated in Right Door Gunner slot, is seated off to their left, this makes it hard for players to see forward of the vehicle and looks rather Jank.
### **Expected Behavior**

- To be seated on the seat, centre of the window, mirrored to the Left Door Gunner's seating position.

### **Screenshots**

![ArmA 3 Screenshot 2021 04 19 - 15 52 45 51](https://user-images.githubusercontent.com/68269584/115259957-3da73a00-a12a-11eb-859f-ff1599afa4fd.png)

- Above is the screenshot of the issue shown. Vehicle in screenshot is the MH-60M, however this is an issue that affects all Helicopters with Door Gunners.

### **Additional context**

- I love your mod, I love you for making it.

**Comment by BroBeansCPG** [comment] 2021-04-19 22:29
Duplicate of #96

**Comment by Halliwedge** [comment] 2021-04-19 22:30
Oh my bad, I searched for dups, obviously not hard enough. My mistake.

**Comment by BroBeansCPG** [comment] 2021-04-19 22:31
All good matey

**Closed as completed** 2021-05-15 16:13 UTC
