### ISSUE TITLE
Feature request: Navigation Way Point Behavior Change

### ISSUE THREAD

**Issue by Tanis1973** [Project-Hatchet/public_h-60#200] opened 2021-11-21 18:50 UTC
The current way point behavior has two options.  All way points must be manually changed or all waypoints automatically change when approximately 200-300 meters away, then switch to next waypoint.  It would be nice if the last waypoint stay rather than disappear on approach.  In limited visibility situations this could be critical such as a bad weather nighttime landing or require a precision landing in a complicated landing zone.

I see a couple options that could satisfy the situation. 
1)  Set the last waypoint to remain until waypoints reset (or have the option to do so), maybe a third upload option?
2)  Allow the map marker to be the last waypoint or appear after the other waypoints are auto selected to the next one.   The map marker would be auto selected last.  Currently the map marker always takes precedence over the loaded map markers.  This may not be the best solution as sometimes you want to go off the waypoint course temporarily using the map click marker.  Being able to delete the waypoints without reuploading from the micro DAGR could mitigate this.

Option 1 is likely the best, and a work around for those that dont like the stickly last waypoint,  set an additional way point (like the exit from LZ waypoint direction to your hold or RTB point).

**Comment by FatLurch** [comment] 2021-12-13 14:05
Perhaps a smaller completion radius for the waypoints could address this: https://community.bistudio.com/wiki/setWaypointCompletionRadius

**Comment by BroBeansCPG** [comment] 2023-02-07 15:00
Kinda dupe of #371 

Needs Nav overhaul

**Closed as completed by BroBeansCPG** 2023-02-07 15:00 UTC
