### ISSUE TITLE
Feature Request: Ability to adjust UI clutter

### ISSUE THREAD

**Issue by Riverman02** [Project-Hatchet/public_h-60#263] opened 2022-01-05 02:55 UTC
Create an add-on option for different levels of interaction with the cockpit. Available options I think would be attractive:

Full: The way it is now. Highlights button/switch with instructions of how to manipulate it

Decluttered: Removes instructions but still highlights the selected button/switch

Minimal/Off: Removes all context outside of the X cursor. Maybe the cursor could change color when over a selectable button/switch

**Comment by BroBeansCPG** [comment] 2022-01-05 11:09
This actually already exists in the latest version of the framework, still need to iron out a major bug before it can be pushed to steam :)

**Comment by Riverman02** [comment] 2022-01-05 12:08
Oh neat!

**Comment by BroBeansCPG** [comment] 2022-01-10 10:40
duplicate of #162

**Closed as completed by BroBeansCPG** 2022-01-10 10:40 UTC
