### ISSUE TITLE
Bug: Crew not taking damage

### ISSUE THREAD

**Issue by 7CavHobbs** [Project-Hatchet/public_h-60#132] opened 2021-04-12 23:16 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this [issue](https://github.com/Project-Hatchet/public_h-60/issues?q=is%3Aissue+label%3Abug+) has not already been filed
- [X] I checked the [FAQ](https://discord.gg/4AYEfFD) and known bugs on the discord

# Bug Report

### **Expected Behavior**
Crew should take damage when shot

### Steps to Reproduce the Issue
1. Shoot the Door Gunner 
2. Shoot the Crew Cheif

**Comment by BroBeansCPG** [comment] 2021-04-13 00:38
Out of curiosity, 

Is this checking the damage of the crew? 

I noticed the other day the pilot doesn’t have a dead/wounded animation so I thought he was still alive

**Comment by 7CavHobbs** [comment] 2021-04-14 12:02
Pilot and co-pilot take damage and die- but no animation

CC and DG don't take damage or die

**Comment by 7CavHobbs** [comment] 2021-05-21 22:37
any update on this issue?

**Comment by A26mike** [comment] 2021-09-10 00:38
Caused by faulty fire geometry Proxies.

**Comment by YannikH** [comment] 2022-09-08 10:52
Should be fixed in 0.6

**Closed as completed by YannikH** 2022-09-08 10:52 UTC
Labels: Type: Bug, Type: Model Issue
